<a href="https://colab.research.google.com/github/BhavikDudhrejiya/Pytorch_Basics/blob/main/Pytorch_Basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch is an open source machine learning framework based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab. It is free and open-source software released under the Modified BSD license. 

In [1]:
#Importing torch library
import torch

# NUMBERS AND FLOAT TENSOR

Tensor is a number, vector, matrix, or any n-dimensional array

In [ ]:
#Creating float tensor
t1 = torch.tensor(4.)
t1

tensor(4.)

In [ ]:
#Checking the data type of tensor
t1.dtype

torch.float32

In [ ]:
#Creating integer tensor
t2 = torch.tensor(4)
t2

tensor(4)

In [ ]:
#Checking the data type of tensor
t2.dtype

torch.int64

# VECTOR TENSOR

In [ ]:
#Creating integer vector
v1 = torch.tensor([1,2,3,4,5,6,7,8,9])
v1

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Checking data type
v1.dtype

torch.int64

In [ ]:
#Creating float vector
v2 = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])
v2

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#Checking data type
v2.dtype

torch.float32

In [ ]:
#Creating float and integer tensor
v3 = torch.tensor([1.0,2,3,4,5,6,7,8,9])
v3

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

#MATRIX TENSOR

In [ ]:
#Creating matrix tensor
m1 = torch.tensor([[5,6],
                  [7,8],
                  [9, 10]])
m1
#This matrix have 3 rows and 2 columns

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
#Checking shape
m1.shape

torch.Size([3, 2])

#ARRAY TENSOR

In [ ]:
#Creating 3d array tensor
a1 = torch.tensor([
                   [[11,12,13],
                    [13, 14, 15]],
                   [[15, 16, 17],
                    [17, 18, 19]]
])

a1

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [ ]:
#Checking shape
a1.shape

torch.Size([2, 2, 3])

#TENSOR OPERATIONS AND GRADIENTS

In [ ]:
#Creating tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
#Arithmetic operation
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
#Compute derivate of x & b w.r.t y
y.backward()

In [ ]:
#Display gradient of the w & b
print(f'dy/dx : {x.grad}')
print(f'dy/dw : {w.grad}')
print(f'dy/db : {b.grad}')

dy/dx : None
dy/dw : 3.0
dy/db : 1.0


In [ ]:
  #Checking data type
  x.dtype, y.dtype, w.dtype, b.dtype

(torch.float32, torch.float32, torch.float32, torch.float32)

#CONVERTING TENSOR INTO NUMPY

In [2]:
#Importing numpy library
import numpy as np

In [ ]:
#Creating numpy array
x = np.array([[1,2], [3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
#Data type
x.dtype

dtype('float64')

In [ ]:
#Converting numpy array into tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
#Data type
y.dtype

torch.float64

In [ ]:
#Converting tensor into numpy
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])